name: Build Windows Installer
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile file_scanner.py
      - name: Install Inno Setup
        run: choco install innosetup  # Using Chocolatey package manager
      - name: Create installer
        run: iscc installer_script.iss  # Your Inno Setup script
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe
